export const CUSTOMMENU = [
  {
    id: 1,
    menu: "Home",
  },
  {
    id: 2,
    menu: "Events",
  },
  {
    id: 3,
    menu: "Organiser",
  },
  {
    id: 4,
    menu: "Contact",
  },
  {
    id: 5,
    menu: "Blog",
  },
  {
    id: 6,
    menu: "Login",
  },
];
export const eventsDropDown = [
  {
    id: 1,
    menu: "All",
  },
  {
    id: 2,
    menu: "Featured",
  },
  {
    id: 3,
    menu: "Festival",
  },
  {
    id: 4,
    menu: "Party",
  },
];

export type EventType = {
  id: number;
  eventThunbnil: string;
  eventType: string;
  dateMonth: string;
  dateDay: string;
  startingFrom: number;
  eventdesc: string;
  longdesc: string;
  lagos: string;
};

export const logoData = [
  { id: 1, src: "/assets/images/uba.jpg", alt: "Company 1" },
  { id: 2, src: "/assets/images/alat.jpg", alt: "Company 2" },
  { id: 3, src: "/assets/images/9pay.jpg", alt: "Company 3" },
  { id: 4, src: "assets/images/uber.jpg", alt: "Company 4" },
  { id: 5, src: "/assets/images/addidas.jpg", alt: "Company 5" },
  { id: 6, src: "/assets/images/coca.jpg", alt: "Company 6" },
  { id: 7, src: "/assets/images/visa.jpg", alt: "Company 7" },
];

export const eventData = [
  {
    id: 1,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "DEC",
    dateDay: "08",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 2,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "DEC",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 3,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "Sep",
    dateDay: "14",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 4,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Featured",
    dateMonth: "Sep",
    dateDay: "20",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 5,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 1000,
    eventdesc: "Happiest One Winterfest 2025",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 6,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "05",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 7,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 8,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "Sep",
    dateDay: "12",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 9,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "Sep",
    dateDay: "15",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 10,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 1000,
    eventdesc: "Happiest One Winterfest 2025",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 11,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Featured",
    dateMonth: "JUN",
    dateDay: "05",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 12,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 13,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Featured",
    dateMonth: "JUN",
    dateDay: "07",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 14,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 15,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 1000,
    eventdesc: "Happiest One Winterfest 2025",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 16,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Featured",
    dateMonth: "JUN",
    dateDay: "05",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 17,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 18,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "07",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 20,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 21,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 22,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 23,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 24,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 25,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 26,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 27,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 28,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 29,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 30,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "07",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 31,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 32,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 33,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 34,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 35,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 36,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 37,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 38,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 39,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  
  {
    id: 40,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "DEC",
    dateDay: "08",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 41,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "DEC",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 42,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "Sep",
    dateDay: "14",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 43,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Featured",
    dateMonth: "Sep",
    dateDay: "20",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 44,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 1000,
    eventdesc: "Happiest One Winterfest 2025",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 6,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "05",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 45,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 46,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "Sep",
    dateDay: "12",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 47,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Party",
    dateMonth: "Sep",
    dateDay: "15",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 48,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 1000,
    eventdesc: "Happiest One Winterfest 2025",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 49,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Featured",
    dateMonth: "JUN",
    dateDay: "05",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 50,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 51,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Featured",
    dateMonth: "JUN",
    dateDay: "07",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 52,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 53,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 1000,
    eventdesc: "Happiest One Winterfest 2025",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 54,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Featured",
    dateMonth: "JUN",
    dateDay: "05",
    startingFrom: 3000,
    eventdesc: "Happiest One Winterfest 2021",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "7 Pm",
  },
  {
    id: 55,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 56,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "07",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 57,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 58,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 59,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 60,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 61,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 62,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 63,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 64,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 65,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 66,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "06",
    startingFrom: 15000,
    eventdesc: "Happiest One Winterfest 2022",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "8 Pm",
  },
  {
    id: 67,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "07",
    startingFrom: 5600,
    eventdesc: "Happiest One Winterfest 2023",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "9 Pm",
  },
  {
    id: 68,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 69,
    eventThunbnil: "assets/images/event2.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },
  {
    id: 70,
    eventThunbnil: "assets/images/event1.png",
    eventType: "Festival",
    dateMonth: "JUN",
    dateDay: "10",
    startingFrom: 8000,
    eventdesc: "Happiest One Winterfest 2024",
    longdesc:
      "Coachable and passionate about collaborating with a team when working on projects",
    lagos: "10 Pm",
  },  

];

export default eventData;

export const TestimonialData = [
  {
    id: 1,
    personProfile: "/assets/images/p1.png",
    rating: 4,
    Desc: "Being able to instantly see the results that my future employer would see! it definitely gave me a sigh of relief.",
    name: "Richoil Global",
    position: "HR Manager",
  },
  {
    id: 2,
    personProfile: "/assets/images/p2.png",
    rating: 3,
    Desc: "I was impressed with how easy it was to navigate through their website and how simple they make it for customers to find what they are looking for ",
    name: "CItiBank Int",
    position: "Managing Director",
  },
  {
    id: 3,
    personProfile: "/assets/images/p3.png",
    rating: 5,
    Desc: "Dossr is transparent, mobile optimized workflow, eConsent, and Comments for Context deliver a 95% satisfaction rating ",
    name: "Delight Customers",
    position: "Social Communication",
  },
  {
    id: 4,
    personProfile: "/assets/images/p1.png",
    rating: 3,
    Desc: "Dossr is transparent, mobile optimized workflow, eConsent, and Comments for Context deliver a 95% satisfaction rating ",
    name: "Delight Customers",
    position: "Social Communication",
  },
];
