import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Dashboard from './Drawer/Drawer'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Dashboard></Dashboard>   
          <div className='ml-3 mr-3'>{children}   </div>    
        </div>
      </body>
    </html>
  )
}
